name: Main

on: [push]

jobs:
  build:
    name: Build and Test (Node.js ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    env:
      CI: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Check Types
        run: yarn type-check

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Upload Code Coverage Results
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
          fail_ci_if_error: true
          verbose: true
